FROM node:25-alpine AS builder
WORKDIR /app
COPY package*.json .
RUN npm ci
COPY . .
RUN npm run build
RUN npm prune --production

FROM node:25-alpine
WORKDIR /app
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/build ./build
EXPOSE ${NODE_PORT}
ENV TRUST_PROXY=true
ENV NODE_ENV=production
CMD [ "node", "build" ]